---
title: Example

message: Hello, world!
lead: Click the button below.
button: Greeting
---

.jumbotron
  @background: white
  .container
    # message
    p
      lead
    p
      .btn
        $click: alert(message)
        button
.container
  Generated by [Plate](https://github.com/tnantoka/plate) {blank} lang.

